const { execSync } = require('child_process');
const fs = require('fs');

const contracts = [
  { name: 'propertyNft', dir: 'temp_nft', wasm: 'game_property_nft.wasm', client: 'PropertyNftClient' },
  { name: 'landToken', dir: 'temp_land', wasm: 'game_land_token.wasm', client: 'LandTokenClient' },
  { name: 'marketplace', dir: 'temp_market', wasm: 'game_marketplace.wasm', client: 'GameMarketplaceClient' },
  { name: 'engine', dir: 'temp_engine', wasm: 'game_engine.wasm', client: 'GameEngineClient' }
];

for (const c of contracts) {
  console.log(`Generating ${c.name}...`);
  execSync(`./stellar contract bindings typescript --wasm apps/contracts/target/wasm32-unknown-unknown/release/${c.wasm} --output-dir ${c.dir} --overwrite`, { stdio: 'inherit' });
  
  let content = fs.readFileSync(`${c.dir}/src/index.ts`, 'utf8');
  
  // Apply our modifications directly
  // 1. Add header
  content = `// Generated by Quasar CLI\n// Post-processing: Renamed Client to ${c.client} to avoid name collisions in barrel exports.\n` + content;
  
  // 2. Rename Client
  content = content.replace(/export interface Client /g, `export interface ${c.client} `);
  content = content.replace(/export class Client extends/g, `export class ${c.client} extends`);
  content = content.replace(/<T = Client>/g, `<T = ${c.client}>`);
  content = content.replace(/initializing a Client/g, `initializing a ${c.client}`);
  
  // 3. Fix txFromJSON error for older TS by casting `this`
  content = content.replace(/this\.txFromJSON/g, '(this as any).txFromJSON');
  
  // 4. Remove window logic
  content = content.replace(/if \(typeof window !== "undefined"\) \{[\s\S]*?\}/g, '');
  
  // 5. Remove wildcard exports to prevent collisions
  content = content.replace(/export \* from "@stellar\/stellar-sdk";\n/g, '');
  content = content.replace(/export \* as contract from "@stellar\/stellar-sdk\/contract";\n/g, '');
  content = content.replace(/export \* as rpc from "@stellar\/stellar-sdk\/rpc";\n/g, '');

  fs.writeFileSync(`apps/shared/src/contracts/game/${c.name}.ts`, content);
  
  // Cleanup
  execSync(`rm -rf ${c.dir}`, { stdio: 'inherit' });
}
console.log("Done.");
