/**
 * @generated PilotIncomeToken typed Soroban client - generated by the Stellar CLI
 * (stellar contract bindings typescript) against apps/contracts/contracts/
 * pilot-income-token.
 *
 * Regenerated to catch up on `mark_wound_down` / `wound_down_status` /
 * `WoundDownRecord` (previously undeclared here despite existing on the
 * contract) and to add two-step admin transfer (transfer_admin_start /
 * transfer_admin_accept / transfer_admin_cancel / pending_admin) and pause
 * parity (pause / unpause / is_paused), issue #1127 (C8-003). Generated
 * from the locally built release WASM (`stellar contract bindings
 * typescript --wasm ...`), not from a live testnet contract: no new
 * deployment has happened yet, so there is no fresh contract ID to
 * regenerate against (the `networks` export from the previous version of
 * this file is dropped for the same reason; nothing in this repo imports
 * it, since contract IDs are resolved from `contracts.testnet.json` at
 * runtime instead). Rebuild the contract and regenerate whenever the
 * interface changes; do not edit by hand.
 *
 * Post-processing applied (C4-015 quality standard):
 *  1. Inlined from the nested generated package into apps/shared/src directly
 *     because the webapp tsconfig uses verbatimModuleSyntax + no DOM lib, making
 *     the generator's default nested-package output unresolvable by Turbopack.
 *  2. `ClientOptions`, `MethodOptions`, `Result` moved to `import type` (TS1484).
 *  3. `window` reference replaced with `globalThis` polyfill guard (TS2304).
 *  4. `override` added to `deploy` and `options` (TS4114 / TS4115).
 *  5. `Timepoint` / `Duration` defined locally as `bigint` aliases - not exported
 *     by `@stellar/stellar-sdk/contract` v13.x (TS2305).
 *  6. No `any` casts used anywhere in this file.
 */
import { Buffer } from "buffer";
import type {
  AssembledTransaction,
  ClientOptions as ContractClientOptions,
  MethodOptions,
} from "@stellar/stellar-sdk/contract";
import {
  Client as ContractClient,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type { u32, u64, i128, Option } from "@stellar/stellar-sdk/contract";

// Timepoint and Duration are not exported by stellar-sdk/contract in v13.x
export type Timepoint = bigint;
export type Duration = bigint;

if (typeof globalThis !== "undefined" && !globalThis.Buffer) {
  (globalThis as typeof globalThis & { Buffer: typeof Buffer }).Buffer = Buffer;
}

/**
 * Durable on-chain record of a permanent pilot wind-down. Written exactly
 * once by `mark_wound_down` and never removed, mirroring the payout-split
 * contract's `ExitRecord` so a client reading either contract independently
 * sees a consistent terminal picture without any cross-contract call.
 */
export interface WoundDownRecord {
  /**
   * Ledger timestamp of the `mark_wound_down` invocation.
   */
  at: u64;
  /**
   * Free-text reason supplied by the admin (see
   * docs/strategy/decision-log.md for the recorded representation decision).
   */
  reason: string;
}

export const IncomeTokenError = {
  1: { message: "AlreadyInitialized" },
  2: { message: "NotInitialized" },
  3: { message: "Unauthorized" },
  4: { message: "AlreadyMinted" },
  5: { message: "EmptyHolderSet" },
  6: { message: "HolderAmountLengthMismatch" },
  7: { message: "InvalidAmount" },
  8: { message: "HolderNotApproved" },
  9: { message: "BalanceOverflow" },
  10: { message: "SupplyOverflow" },
  11: { message: "InsufficientBalance" },
  12: { message: "InternalInvariant" },
  /**
   * The pilot has already been marked wound down; the marker is one-way.
   */
  13: { message: "AlreadyWoundDown" },
  /**
   * `mark_wound_down` was invoked without a non-empty reason string.
   */
  14: { message: "MissingWoundDownReason" },
  /**
   * `transfer_admin_accept` was called by an address that does not match
   * the pending admin recorded by `transfer_admin_start`, or no transfer
   * is pending at all.
   */
  15: { message: "NotPendingAdmin" },
  /**
   * A state-changing call was rejected because the contract is paused.
   */
  16: { message: "ContractPaused" },
};

export interface MintedEvent {
  admin: string;
  holder_count: u32;
  total_supply: i128;
}

export interface TransferEvent {
  amount: i128;
  from: string;
  to: string;
}

export interface TokenInitializedEvent {
  admin: string;
  whitelist: string;
}

/**
 * Emitted once when the pilot is permanently marked wound down.
 */
export interface WoundDownRecordedEvent {
  admin: string;
  at: u64;
  reason: string;
}

export interface AdminTransferStartedEvent {
  current_admin: string;
  new_admin: string;
}

export interface AdminTransferAcceptedEvent {
  new_admin: string;
  old_admin: string;
}

export interface AdminTransferCancelledEvent {
  admin: string;
}

export type DataKey =
  | { tag: "Admin"; values: void }
  | { tag: "Whitelist"; values: void }
  | { tag: "Name"; values: void }
  | { tag: "Symbol"; values: void }
  | { tag: "Decimals"; values: void }
  | { tag: "TotalSupply"; values: void }
  | { tag: "Balance"; values: readonly [string] }
  | { tag: "Holders"; values: void }
  | { tag: "Minted"; values: void }
  | { tag: "WoundDown"; values: void }
  | { tag: "PendingAdmin"; values: void }
  | { tag: "Paused"; values: void };

export interface PilotIncomeTokenClientInterface {
  /**
   * Return token name.
   */
  name: (options?: MethodOptions) => Promise<AssembledTransaction<string>>;

  /**
   * Return the configured token admin.
   */
  admin: (options?: MethodOptions) => Promise<AssembledTransaction<string>>;

  /**
   * Pause `mint_fixed_supply`, `transfer`, and `mark_wound_down`.
   * Read-only calls (`balance`, `holders`, `total_supply`, and the rest)
   * keep working.
   *
   * Mirrors `pilot-payout-split`'s `pause`. Before this change, a
   * wrongful mint or correction transfer had no on-chain circuit breaker.
   */
  pause: (
    { admin }: { admin: string },
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Return token symbol.
   */
  symbol: (options?: MethodOptions) => Promise<AssembledTransaction<string>>;

  /**
   * Return the balance of an address.
   */
  balance: (
    { id }: { id: string },
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<i128>>;

  /**
   * Return the fixed holder set used by payout distribution.
   */
  holders: (
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<Array<string>>>;

  /**
   * Resume `mint_fixed_supply`, `transfer`, and `mark_wound_down`.
   */
  unpause: (
    { admin }: { admin: string },
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Return token decimal precision.
   */
  decimals: (options?: MethodOptions) => Promise<AssembledTransaction<u32>>;

  /**
   * Admin-only correction transfer. Holders cannot transfer the token.
   */
  transfer: (
    {
      caller,
      from,
      to,
      amount,
    }: { caller: string; from: string; to: string; amount: i128 },
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Return whether the contract is paused.
   */
  is_paused: (options?: MethodOptions) => Promise<AssembledTransaction<boolean>>;

  /**
   * Initialize token metadata and the whitelist contract used for mint gating.
   */
  initialize: (
    {
      admin,
      whitelist,
      name,
      symbol,
      decimals,
    }: {
      admin: string;
      whitelist: string;
      name: string;
      symbol: string;
      decimals: u32;
    },
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Return total minted supply.
   */
  total_supply: (
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<i128>>;

  /**
   * Return the pending admin, if a transfer is in progress.
   */
  pending_admin: (
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<Option<string>>>;

  /**
   * Permanently mark the pilot as wound down.
   *
   * One-way and irreversible: once set, the marker can never be cleared and
   * no un-wind-down function exists. Admin-gated, matching every other
   * state-changing function on this contract, so the same platform key that
   * mints and corrects balances owns the terminal state too.
   *
   * This is an independent write from `exit` on the payout-split contract:
   * each contract stores and exposes its own terminal marker, so a client
   * reading either contract alone gets a complete answer without a
   * cross-contract call at read time. Recording the fact of wind-down only;
   * no fund-recovery, refund, or unwind logic is implemented here (that
   * remains an open product/legal question, Known Risk #5 in the product
   * brief).
   */
  mark_wound_down: (
    { admin, reason }: { admin: string; reason: string },
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Mint the fixed pilot supply once to approved holders.
   */
  mint_fixed_supply: (
    {
      admin,
      holders,
      amounts,
    }: { admin: string; holders: Array<string>; amounts: Array<i128> },
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Return the terminal wound-down record, or `None` while the pilot is
   * active. Read-only and self-contained: no cross-contract call is needed.
   */
  wound_down_status: (
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<Option<WoundDownRecord>>>;

  /**
   * Begin transferring admin to a new address.
   *
   * Two-step, following the same pattern as `defi-rwa`'s
   * `AdminControl::transfer_admin_start` (see
   * docs/operations/runbook-role-management.md). The current admin keeps
   * full control until `new_admin` calls `transfer_admin_accept`, so a
   * mistyped or unreachable new admin can never lock the contract out.
   * Not blocked by `pause`: admin recovery must keep working while paused.
   */
  transfer_admin_start: (
    { caller, new_admin }: { caller: string; new_admin: string },
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Accept a pending admin transfer. Must be signed by the address named
   * in `transfer_admin_start`. The old admin loses every privilege the
   * instant this call succeeds, since `require_admin` compares against the
   * single stored admin address.
   */
  transfer_admin_accept: (
    { new_admin }: { new_admin: string },
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<null>>;

  /**
   * Cancel a pending admin transfer before it is accepted. Only the
   * current admin can cancel.
   */
  transfer_admin_cancel: (
    { caller }: { caller: string },
    options?: MethodOptions,
  ) => Promise<AssembledTransaction<null>>;
}

export class PilotIncomeTokenClient extends ContractClient {
  static override async deploy<T = PilotIncomeTokenClient>(
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        wasmHash: Buffer | string;
        salt?: Buffer | Uint8Array;
        format?: "hex" | "base64";
      },
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options);
  }

  constructor(public override readonly options: ContractClientOptions) {
    super(
      new ContractSpec([
        "AAAAAAAAABJSZXR1cm4gdG9rZW4gbmFtZS4AAAAAAARuYW1lAAAAAAAAAAEAAAAQ",
        "AAAAAAAAACJSZXR1cm4gdGhlIGNvbmZpZ3VyZWQgdG9rZW4gYWRtaW4uAAAAAAAFYWRtaW4AAAAAAAAAAAAAAQAAABM=",
        "AAAAAAAAARVQYXVzZSBgbWludF9maXhlZF9zdXBwbHlgLCBgdHJhbnNmZXJgLCBhbmQgYG1hcmtfd291bmRfZG93bmAuClJlYWQtb25seSBjYWxscyAoYGJhbGFuY2VgLCBgaG9sZGVyc2AsIGB0b3RhbF9zdXBwbHlgLCBhbmQgdGhlIHJlc3QpCmtlZXAgd29ya2luZy4KCk1pcnJvcnMgYHBpbG90LXBheW91dC1zcGxpdGAncyBgcGF1c2VgLiBCZWZvcmUgdGhpcyBjaGFuZ2UsIGEKd3JvbmdmdWwgbWludCBvciBjb3JyZWN0aW9uIHRyYW5zZmVyIGhhZCBubyBvbi1jaGFpbiBjaXJjdWl0IGJyZWFrZXIuAAAAAAAABXBhdXNlAAAAAAAAAQAAAAAAAAAFYWRtaW4AAAAAAAATAAAAAA==",
        "AAAAAQAAAR1EdXJhYmxlIG9uLWNoYWluIHJlY29yZCBvZiBhIHBlcm1hbmVudCBwaWxvdCB3aW5kLWRvd24uIFdyaXR0ZW4gZXhhY3RseQpvbmNlIGJ5IGBtYXJrX3dvdW5kX2Rvd25gIGFuZCBuZXZlciByZW1vdmVkLCBtaXJyb3JpbmcgdGhlIHBheW91dC1zcGxpdApjb250cmFjdCdzIGBFeGl0UmVjb3JkYCBzbyBhIGNsaWVudCByZWFkaW5nIGVpdGhlciBjb250cmFjdCBpbmRlcGVuZGVudGx5CnNlZXMgYSBjb25zaXN0ZW50IHRlcm1pbmFsIHBpY3R1cmUgd2l0aG91dCBhbnkgY3Jvc3MtY29udHJhY3QgY2FsbC4AAAAAAAAAAAAAD1dvdW5kRG93blJlY29yZAAAAAACAAAANUxlZGdlciB0aW1lc3RhbXAgb2YgdGhlIGBtYXJrX3dvdW5kX2Rvd25gIGludm9jYXRpb24uAAAAAAAAAmF0AAAAAAAGAAAAdEZyZWUtdGV4dCByZWFzb24gc3VwcGxpZWQgYnkgdGhlIGFkbWluIChzZWUKZG9jcy9zdHJhdGVneS9kZWNpc2lvbi1sb2cubWQgZm9yIHRoZSByZWNvcmRlZCByZXByZXNlbnRhdGlvbiBkZWNpc2lvbikuAAAABnJlYXNvbgAAAAAAEA==",
        "AAAAAAAAABRSZXR1cm4gdG9rZW4gc3ltYm9sLgAAAAZzeW1ib2wAAAAAAAAAAAABAAAAEA==",
        "AAAAAAAAACFSZXR1cm4gdGhlIGJhbGFuY2Ugb2YgYW4gYWRkcmVzcy4AAAAAAAAHYmFsYW5jZQAAAAABAAAAAAAAAAJpZAAAAAAAEwAAAAEAAAAL",
        "AAAAAAAAADhSZXR1cm4gdGhlIGZpeGVkIGhvbGRlciBzZXQgdXNlZCBieSBwYXlvdXQgZGlzdHJpYnV0aW9uLgAAAAdob2xkZXJzAAAAAAAAAAABAAAD6gAAABM=",
        "AAAAAAAAAD5SZXN1bWUgYG1pbnRfZml4ZWRfc3VwcGx5YCwgYHRyYW5zZmVyYCwgYW5kIGBtYXJrX3dvdW5kX2Rvd25gLgAAAAAAB3VucGF1c2UAAAAAAQAAAAAAAAAFYWRtaW4AAAAAAAATAAAAAA==",
        "AAAAAAAAAB9SZXR1cm4gdG9rZW4gZGVjaW1hbCBwcmVjaXNpb24uAAAAAAhkZWNpbWFscwAAAAAAAAABAAAABA==",
        "AAAAAAAAAEJBZG1pbi1vbmx5IGNvcnJlY3Rpb24gdHJhbnNmZXIuIEhvbGRlcnMgY2Fubm90IHRyYW5zZmVyIHRoZSB0b2tlbi4AAAAAAAh0cmFuc2ZlcgAAAAQAAAAAAAAABmNhbGxlcgAAAAAAEwAAAAAAAAAEZnJvbQAAABMAAAAAAAAAAnRvAAAAAAATAAAAAAAAAAZhbW91bnQAAAAAAAsAAAAA",
        "AAAAAAAAACZSZXR1cm4gd2hldGhlciB0aGUgY29udHJhY3QgaXMgcGF1c2VkLgAAAAAACWlzX3BhdXNlZAAAAAAAAAAAAAABAAAAAQ==",
        "AAAAAAAAAEpJbml0aWFsaXplIHRva2VuIG1ldGFkYXRhIGFuZCB0aGUgd2hpdGVsaXN0IGNvbnRyYWN0IHVzZWQgZm9yIG1pbnQgZ2F0aW5nLgAAAAAACmluaXRpYWxpemUAAAAAAAUAAAAAAAAABWFkbWluAAAAAAAAEwAAAAAAAAAJd2hpdGVsaXN0AAAAAAAAEwAAAAAAAAAEbmFtZQAAABAAAAAAAAAABnN5bWJvbAAAAAAAEAAAAAAAAAAIZGVjaW1hbHMAAAAEAAAAAA==",
        "AAAAAAAAABtSZXR1cm4gdG90YWwgbWludGVkIHN1cHBseS4AAAAADHRvdGFsX3N1cHBseQAAAAAAAAABAAAACw==",
        "AAAAAAAAADdSZXR1cm4gdGhlIHBlbmRpbmcgYWRtaW4sIGlmIGEgdHJhbnNmZXIgaXMgaW4gcHJvZ3Jlc3MuAAAAAA1wZW5kaW5nX2FkbWluAAAAAAAAAAAAAAEAAAPoAAAAEw==",
        "AAAAAAAAAtxQZXJtYW5lbnRseSBtYXJrIHRoZSBwaWxvdCBhcyB3b3VuZCBkb3duLgoKT25lLXdheSBhbmQgaXJyZXZlcnNpYmxlOiBvbmNlIHNldCwgdGhlIG1hcmtlciBjYW4gbmV2ZXIgYmUgY2xlYXJlZCBhbmQKbm8gdW4td2luZC1kb3duIGZ1bmN0aW9uIGV4aXN0cy4gQWRtaW4tZ2F0ZWQsIG1hdGNoaW5nIGV2ZXJ5IG90aGVyCnN0YXRlLWNoYW5naW5nIGZ1bmN0aW9uIG9uIHRoaXMgY29udHJhY3QsIHNvIHRoZSBzYW1lIHBsYXRmb3JtIGtleSB0aGF0Cm1pbnRzIGFuZCBjb3JyZWN0cyBiYWxhbmNlcyBvd25zIHRoZSB0ZXJtaW5hbCBzdGF0ZSB0b28uCgpUaGlzIGlzIGFuIGluZGVwZW5kZW50IHdyaXRlIGZyb20gYGV4aXRgIG9uIHRoZSBwYXlvdXQtc3BsaXQgY29udHJhY3Q6CmVhY2ggY29udHJhY3Qgc3RvcmVzIGFuZCBleHBvc2VzIGl0cyBvd24gdGVybWluYWwgbWFya2VyLCBzbyBhIGNsaWVudApyZWFkaW5nIGVpdGhlciBjb250cmFjdCBhbG9uZSBnZXRzIGEgY29tcGxldGUgYW5zd2VyIHdpdGhvdXQgYQpjcm9zcy1jb250cmFjdCBjYWxsIGF0IHJlYWQgdGltZS4gUmVjb3JkaW5nIHRoZSBmYWN0IG9mIHdpbmQtZG93biBvbmx5OwpubyBmdW5kLXJlY292ZXJ5LCByZWZ1bmQsIG9yIHVud2luZCBsb2dpYyBpcyBpbXBsZW1lbnRlZCBoZXJlICh0aGF0CnJlbWFpbnMgYW4gb3BlbiBwcm9kdWN0L2xlZ2FsIHF1ZXN0aW9uLCBLbm93biBSaXNrICM1IGluIHRoZSBwcm9kdWN0CmJyaWVmKS4AAAAPbWFya193b3VuZF9kb3duAAAAAAIAAAAAAAAABWFkbWluAAAAAAAAEwAAAAAAAAAGcmVhc29uAAAAAAAQAAAAAA==",
        "AAAAAAAAADVNaW50IHRoZSBmaXhlZCBwaWxvdCBzdXBwbHkgb25jZSB0byBhcHByb3ZlZCBob2xkZXJzLgAAAAAAABFtaW50X2ZpeGVkX3N1cHBseQAAAAAAAAMAAAAAAAAABWFkbWluAAAAAAAAEwAAAAAAAAAHaG9sZGVycwAAAAPqAAAAEwAAAAAAAAAHYW1vdW50cwAAAAPqAAAACwAAAAA=",
        "AAAAAAAAAItSZXR1cm4gdGhlIHRlcm1pbmFsIHdvdW5kLWRvd24gcmVjb3JkLCBvciBgTm9uZWAgd2hpbGUgdGhlIHBpbG90IGlzCmFjdGl2ZS4gUmVhZC1vbmx5IGFuZCBzZWxmLWNvbnRhaW5lZDogbm8gY3Jvc3MtY29udHJhY3QgY2FsbCBpcyBuZWVkZWQuAAAAABF3b3VuZF9kb3duX3N0YXR1cwAAAAAAAAAAAAABAAAD6AAAB9AAAAAPV291bmREb3duUmVjb3JkAA==",
        "AAAAAAAAAZxCZWdpbiB0cmFuc2ZlcnJpbmcgYWRtaW4gdG8gYSBuZXcgYWRkcmVzcy4KClR3by1zdGVwLCBmb2xsb3dpbmcgdGhlIHNhbWUgcGF0dGVybiBhcyBgZGVmaS1yd2FgJ3MKYEFkbWluQ29udHJvbDo6dHJhbnNmZXJfYWRtaW5fc3RhcnRgIChzZWUKZG9jcy9vcGVyYXRpb25zL3J1bmJvb2stcm9sZS1tYW5hZ2VtZW50Lm1kKS4gVGhlIGN1cnJlbnQgYWRtaW4ga2VlcHMKZnVsbCBjb250cm9sIHVudGlsIGBuZXdfYWRtaW5gIGNhbGxzIGB0cmFuc2Zlcl9hZG1pbl9hY2NlcHRgLCBzbyBhCm1pc3R5cGVkIG9yIHVucmVhY2hhYmxlIG5ldyBhZG1pbiBjYW4gbmV2ZXIgbG9jayB0aGUgY29udHJhY3Qgb3V0LgpOb3QgYmxvY2tlZCBieSBgcGF1c2VgOiBhZG1pbiByZWNvdmVyeSBtdXN0IGtlZXAgd29ya2luZyB3aGlsZSBwYXVzZWQuAAAAFHRyYW5zZmVyX2FkbWluX3N0YXJ0AAAAAgAAAAAAAAAGY2FsbGVyAAAAAAATAAAAAAAAAAluZXdfYWRtaW4AAAAAAAATAAAAAA==",
        "AAAAAAAAAOtBY2NlcHQgYSBwZW5kaW5nIGFkbWluIHRyYW5zZmVyLiBNdXN0IGJlIHNpZ25lZCBieSB0aGUgYWRkcmVzcyBuYW1lZAppbiBgdHJhbnNmZXJfYWRtaW5fc3RhcnRgLiBUaGUgb2xkIGFkbWluIGxvc2VzIGV2ZXJ5IHByaXZpbGVnZSB0aGUKaW5zdGFudCB0aGlzIGNhbGwgc3VjY2VlZHMsIHNpbmNlIGByZXF1aXJlX2FkbWluYCBjb21wYXJlcyBhZ2FpbnN0IHRoZQpzaW5nbGUgc3RvcmVkIGFkbWluIGFkZHJlc3MuAAAAABV0cmFuc2Zlcl9hZG1pbl9hY2NlcHQAAAAAAAABAAAAAAAAAAluZXdfYWRtaW4AAAAAAAATAAAAAA==",
        "AAAAAAAAAFlDYW5jZWwgYSBwZW5kaW5nIGFkbWluIHRyYW5zZmVyIGJlZm9yZSBpdCBpcyBhY2NlcHRlZC4gT25seSB0aGUKY3VycmVudCBhZG1pbiBjYW4gY2FuY2VsLgAAAAAAABV0cmFuc2Zlcl9hZG1pbl9jYW5jZWwAAAAAAAABAAAAAAAAAAZjYWxsZXIAAAAAABMAAAAA",
        "AAAABAAAAAAAAAAAAAAAEEluY29tZVRva2VuRXJyb3IAAAAQAAAAAAAAABJBbHJlYWR5SW5pdGlhbGl6ZWQAAAAAAAEAAAAAAAAADk5vdEluaXRpYWxpemVkAAAAAAACAAAAAAAAAAxVbmF1dGhvcml6ZWQAAAADAAAAAAAAAA1BbHJlYWR5TWludGVkAAAAAAAABAAAAAAAAAAORW1wdHlIb2xkZXJTZXQAAAAAAAUAAAAAAAAAGkhvbGRlckFtb3VudExlbmd0aE1pc21hdGNoAAAAAAAGAAAAAAAAAA1JbnZhbGlkQW1vdW50AAAAAAAABwAAAAAAAAARSG9sZGVyTm90QXBwcm92ZWQAAAAAAAAIAAAAAAAAAA9CYWxhbmNlT3ZlcmZsb3cAAAAACQAAAAAAAAAOU3VwcGx5T3ZlcmZsb3cAAAAAAAoAAAAAAAAAE0luc3VmZmljaWVudEJhbGFuY2UAAAAACwAAAAAAAAARSW50ZXJuYWxJbnZhcmlhbnQAAAAAAAAMAAAARFRoZSBwaWxvdCBoYXMgYWxyZWFkeSBiZWVuIG1hcmtlZCB3b3VuZCBkb3duOyB0aGUgbWFya2VyIGlzIG9uZS13YXkuAAAAEEFscmVhZHlXb3VuZERvd24AAAANAAAAQGBtYXJrX3dvdW5kX2Rvd25gIHdhcyBpbnZva2VkIHdpdGhvdXQgYSBub24tZW1wdHkgcmVhc29uIHN0cmluZy4AAAAWTWlzc2luZ1dvdW5kRG93blJlYXNvbgAAAAAADgAAAJxgdHJhbnNmZXJfYWRtaW5fYWNjZXB0YCB3YXMgY2FsbGVkIGJ5IGFuIGFkZHJlc3MgdGhhdCBkb2VzIG5vdCBtYXRjaAp0aGUgcGVuZGluZyBhZG1pbiByZWNvcmRlZCBieSBgdHJhbnNmZXJfYWRtaW5fc3RhcnRgLCBvciBubyB0cmFuc2ZlcgppcyBwZW5kaW5nIGF0IGFsbC4AAAAPTm90UGVuZGluZ0FkbWluAAAAAA8AAABCQSBzdGF0ZS1jaGFuZ2luZyBjYWxsIHdhcyByZWplY3RlZCBiZWNhdXNlIHRoZSBjb250cmFjdCBpcyBwYXVzZWQuAAAAAAAOQ29udHJhY3RQYXVzZWQAAAAAABA=",
        "AAAAAQAAAAAAAAAAAAAAC01pbnRlZEV2ZW50AAAAAAMAAAAAAAAABWFkbWluAAAAAAAAEwAAAAAAAAAMaG9sZGVyX2NvdW50AAAABAAAAAAAAAAMdG90YWxfc3VwcGx5AAAACw==",
        "AAAAAQAAAAAAAAAAAAAADVRyYW5zZmVyRXZlbnQAAAAAAAADAAAAAAAAAAZhbW91bnQAAAAAAAsAAAAAAAAABGZyb20AAAATAAAAAAAAAAJ0bwAAAAAAEw==",
        "AAAAAQAAAAAAAAAAAAAAFVRva2VuSW5pdGlhbGl6ZWRFdmVudAAAAAAAAAIAAAAAAAAABWFkbWluAAAAAAAAEwAAAAAAAAAJd2hpdGVsaXN0AAAAAAAAEw==",
        "AAAAAQAAAD1FbWl0dGVkIG9uY2Ugd2hlbiB0aGUgcGlsb3QgaXMgcGVybWFuZW50bHkgbWFya2VkIHdvdW5kIGRvd24uAAAAAAAAAAAAABZXb3VuZERvd25SZWNvcmRlZEV2ZW50AAAAAAADAAAAAAAAAAVhZG1pbgAAAAAAABMAAAAAAAAAAmF0AAAAAAAGAAAAAAAAAAZyZWFzb24AAAAAABA=",
        "AAAAAQAAAAAAAAAAAAAAGUFkbWluVHJhbnNmZXJTdGFydGVkRXZlbnQAAAAAAAACAAAAAAAAAA1jdXJyZW50X2FkbWluAAAAAAAAEwAAAAAAAAAJbmV3X2FkbWluAAAAAAAAEw==",
        "AAAAAQAAAAAAAAAAAAAAGkFkbWluVHJhbnNmZXJBY2NlcHRlZEV2ZW50AAAAAAACAAAAAAAAAAluZXdfYWRtaW4AAAAAAAATAAAAAAAAAAlvbGRfYWRtaW4AAAAAAAAT",
        "AAAAAQAAAAAAAAAAAAAAG0FkbWluVHJhbnNmZXJDYW5jZWxsZWRFdmVudAAAAAABAAAAAAAAAAVhZG1pbgAAAAAAABM=",
        "AAAAAgAAAAAAAAAAAAAAB0RhdGFLZXkAAAAADAAAAAAAAAAAAAAABUFkbWluAAAAAAAAAAAAAAAAAAAJV2hpdGVsaXN0AAAAAAAAAAAAAAAAAAAETmFtZQAAAAAAAAAAAAAABlN5bWJvbAAAAAAAAAAAAAAAAAAIRGVjaW1hbHMAAAAAAAAAAAAAAAtUb3RhbFN1cHBseQAAAAABAAAAAAAAAAdCYWxhbmNlAAAAAAEAAAATAAAAAAAAAAAAAAAHSG9sZGVycwAAAAAAAAAAAAAAAAZNaW50ZWQAAAAAAAAAAAAAAAAACVdvdW5kRG93bgAAAAAAAAAAAAAAAAAADFBlbmRpbmdBZG1pbgAAAAAAAAAAAAAABlBhdXNlZAAA",
      ]),
      options,
    );
  }

  public readonly fromJSON = {
    name: this.txFromJSON<string>,
    admin: this.txFromJSON<string>,
    pause: this.txFromJSON<null>,
    symbol: this.txFromJSON<string>,
    balance: this.txFromJSON<i128>,
    holders: this.txFromJSON<Array<string>>,
    unpause: this.txFromJSON<null>,
    decimals: this.txFromJSON<u32>,
    transfer: this.txFromJSON<null>,
    is_paused: this.txFromJSON<boolean>,
    initialize: this.txFromJSON<null>,
    total_supply: this.txFromJSON<i128>,
    pending_admin: this.txFromJSON<Option<string>>,
    mark_wound_down: this.txFromJSON<null>,
    mint_fixed_supply: this.txFromJSON<null>,
    wound_down_status: this.txFromJSON<Option<WoundDownRecord>>,
    transfer_admin_start: this.txFromJSON<null>,
    transfer_admin_accept: this.txFromJSON<null>,
    transfer_admin_cancel: this.txFromJSON<null>,
  };
}
