/**
 * @generated GameEngine typed Soroban client — generated by the Quasar CLI
 * (stellar contract bindings typescript) from the compiled WASM artifact at
 * apps/contracts/target/wasm32-unknown-unknown/release/game_engine.wasm.
 *
 * Post-processing applied (C4-015 quality standard):
 *  1. Inlined from the nested generated package into apps/shared/src directly
 *     because the webapp tsconfig uses verbatimModuleSyntax + no DOM lib, making
 *     the generator's default nested-package output unresolvable by Turbopack.
 *  2. `ClientOptions`, `MethodOptions`, `Result` moved to `import type` (TS1484).
 *  3. `window` reference replaced with `globalThis` polyfill guard (TS2304).
 *  4. `override` added to `deploy` and `options` (TS4114 / TS4115).
 *  5. `Timepoint` / `Duration` defined locally as `bigint` aliases — not exported
 *     by `@stellar/stellar-sdk/contract` v13.x (TS2305).
 *  6. No `any` casts used anywhere in this file.
 */
import { Buffer } from "buffer";
import type {
  AssembledTransaction,
  ClientOptions as ContractClientOptions,
  MethodOptions,
} from "@stellar/stellar-sdk/contract";
import {
  Client as ContractClient,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type { u32, u64, i128 } from "@stellar/stellar-sdk/contract";

// Timepoint and Duration are not exported by stellar-sdk/contract in v13.x
export type Timepoint = bigint;
export type Duration = bigint;

if (typeof globalThis !== "undefined" && !globalThis.Buffer) {
  (globalThis as typeof globalThis & { Buffer: typeof Buffer }).Buffer = Buffer;
}

export type StorageKey =
  | { tag: "NftContract"; values: void }
  | { tag: "TokenContract"; values: void }
  | { tag: "Treasury"; values: void }
  | { tag: "Initialized"; values: void };

export const EngineError = {
  1: { message: "AlreadyInitialized" },
  2: { message: "NotOwner" },
  3: { message: "AlreadyMaxLevel" },
  4: { message: "NothingToClaim" },
  5: { message: "InsufficientBalance" },
};

export interface PropertyState {
  approved: string | null;
  id: u32;
  last_claimed_ledger: u64;
  level: u32;
  owner: string;
  x: u32;
  y: u32;
}

export class EngineClient extends ContractClient {
  static override async deploy<T = EngineClient>(
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        wasmHash: Buffer | string;
        salt?: Buffer | Uint8Array;
        format?: "hex" | "base64";
      },
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options);
  }

  constructor(public override readonly options: ContractClientOptions) {
    super(
      new ContractSpec([
        "AAAAAgAAAAAAAAAAAAAAClN0b3JhZ2VLZXkAAAAAAAQAAAAAAAAAAAAAAAtOZnRDb250cmFjdAAAAAAAAAAAAAAAAA1Ub2tlbkNvbnRyYWN0AAAAAAAAAAAAAAAAAAAIVHJlYXN1cnkAAAAAAAAAAAAAAAtJbml0aWFsaXplZAA=",
        "AAAAAAAAAAAAAAAHaW1wcm92ZQAAAAACAAAAAAAAAAZjYWxsZXIAAAAAABMAAAAAAAAAC3Byb3BlcnR5X2lkAAAAAAQAAAAA",
        "AAAABAAAAAAAAAAAAAAAC0VuZ2luZUVycm9yAAAAAAUAAAAAAAAAEkFscmVhZHlJbml0aWFsaXplZAAAAAAAAQAAAAAAAAAITm90T3duZXIAAAACAAAAAAAAAA9BbHJlYWR5TWF4TGV2ZWwAAAAAAwAAAAAAAAAOTm90aGluZ1RvQ2xhaW0AAAAAAAQAAAAAAAAAE0luc3VmZmljaWVudEJhbGFuY2UAAAAABQ==",
        "AAAAAQAAAAAAAAAAAAAADVByb3BlcnR5U3RhdGUAAAAAAAAHAAAAAAAAAAhhcHByb3ZlZAAAA+gAAAATAAAAAAAAAAJpZAAAAAAABAAAAAAAAAATbGFzdF9jbGFpbWVkX2xlZGdlcgAAAAAGAAAAAAAAAAVsZXZlbAAAAAAAAAQAAAAAAAAABW93bmVyAAAAAAAAEwAAAAAAAAABeAAAAAAAAAQAAAAAAAAAAXkAAAAAAAAE",
        "AAAAAAAAAAAAAAAKaW5pdGlhbGl6ZQAAAAAAAwAAAAAAAAAMbmZ0X2NvbnRyYWN0AAAAEwAAAAAAAAAOdG9rZW5fY29udHJhY3QAAAAAABMAAAAAAAAACHRyZWFzdXJ5AAAAEwAAAAA=",
        "AAAAAAAAAAAAAAAMY2xhaW1fcmVudGFsAAAAAgAAAAAAAAAGY2FsbGVyAAAAAAATAAAAAAAAAAtwcm9wZXJ0eV9pZAAAAAAEAAAAAA==",
        "AAAAAAAAAAAAAAASZ2V0X2FjY3J1ZWRfaW5jb21lAAAAAAABAAAAAAAAAAtwcm9wZXJ0eV9pZAAAAAAEAAAAAQAAAAs=",
      ]),
      options,
    );
  }

  public readonly fromJSON = {
    improve: this.txFromJSON<null>,
    initialize: this.txFromJSON<null>,
    claim_rental: this.txFromJSON<null>,
    get_accrued_income: this.txFromJSON<i128>,
  };
}
