/**
 * @generated LandToken typed Soroban client — generated by the Quasar CLI
 * (stellar contract bindings typescript) from the compiled WASM artifact at
 * apps/contracts/target/wasm32-unknown-unknown/release/game_land_token.wasm.
 *
 * Post-processing applied (C4-015 quality standard):
 *  1. Inlined from the nested generated package into apps/shared/src directly
 *     because the webapp tsconfig uses verbatimModuleSyntax + no DOM lib, making
 *     the generator's default nested-package output unresolvable by Turbopack.
 *  2. `ClientOptions`, `MethodOptions`, `Result` moved to `import type` (TS1484).
 *  3. `window` reference replaced with `globalThis` polyfill guard (TS2304).
 *  4. `override` added to `deploy` and `options` (TS4114 / TS4115).
 *  5. `Timepoint` / `Duration` defined locally as `bigint` aliases — not exported
 *     by `@stellar/stellar-sdk/contract` v13.x (TS2305).
 *  6. No `any` casts used anywhere in this file.
 */
import { Buffer } from "buffer";
import type {
  AssembledTransaction,
  ClientOptions as ContractClientOptions,
  MethodOptions,
} from "@stellar/stellar-sdk/contract";
import {
  Client as ContractClient,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";
import type { u32, i128 } from "@stellar/stellar-sdk/contract";

// Timepoint and Duration are not exported by stellar-sdk/contract in v13.x
export type Timepoint = bigint;
export type Duration = bigint;

if (typeof globalThis !== "undefined" && !globalThis.Buffer) {
  (globalThis as typeof globalThis & { Buffer: typeof Buffer }).Buffer = Buffer;
}

export type DataKey =
  | { tag: "Balance"; values: readonly [string] }
  | { tag: "Allowance"; values: readonly [string, string] }
  | { tag: "Admin"; values: void }
  | { tag: "Testnet"; values: void }
  | { tag: "Authorized"; values: readonly [string] }
  | { tag: "FaucetClaimed"; values: readonly [string] };

export const TokenError = {
  1: { message: "AlreadyInitialized" },
  2: { message: "InsufficientBalance" },
  3: { message: "InsufficientAllowance" },
  4: { message: "FaucetDisabled" },
  5: { message: "FaucetAlreadyClaimed" },
  6: { message: "Unauthorized" },
};

export class LandTokenClient extends ContractClient {
  static override async deploy<T = LandTokenClient>(
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        wasmHash: Buffer | string;
        salt?: Buffer | Uint8Array;
        format?: "hex" | "base64";
      },
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options);
  }

  constructor(public override readonly options: ContractClientOptions) {
    super(
      new ContractSpec([
        "AAAAAgAAAAAAAAAAAAAAB0RhdGFLZXkAAAAABgAAAAEAAAAAAAAAB0JhbGFuY2UAAAAAAQAAABMAAAABAAAAAAAAAAlBbGxvd2FuY2UAAAAAAAACAAAAEwAAABMAAAAAAAAAAAAAAAVBZG1pbgAAAAAAAAAAAAAAAAAAB1Rlc3RuZXQAAAAAAQAAAAAAAAAKQXV0aG9yaXplZAAAAAAAAQAAABMAAAABAAAAAAAAAA1GYXVjZXRDbGFpbWVkAAAAAAAAAQAAABM=",
        "AAAABAAAAAAAAAAAAAAAClRva2VuRXJyb3IAAAAAAAYAAAAAAAAAEkFscmVhZHlJbml0aWFsaXplZAAAAAAAAQAAAAAAAAATSW5zdWZmaWNpZW50QmFsYW5jZQAAAAACAAAAAAAAABVJbnN1ZmZpY2llbnRBbGxvd2FuY2UAAAAAAAADAAAAAAAAAA5GYXVjZXREaXNhYmxlZAAAAAAABAAAAAAAAAAURmF1Y2V0QWxyZWFkeUNsYWltZWQAAAAFAAAAAAAAAAxVbmF1dGhvcml6ZWQAAAAG",
        "AAAAAAAAAAAAAAAEYnVybgAAAAIAAAAAAAAABGZyb20AAAATAAAAAAAAAAZhbW91bnQAAAAAAAsAAAAA",
        "AAAAAAAAAAAAAAAEbWludAAAAAMAAAAAAAAABmNhbGxlcgAAAAAAEwAAAAAAAAACdG8AAAAAABMAAAAAAAAABmFtb3VudAAAAAAACwAAAAA=",
        "AAAAAAAAAAAAAAAEbmFtZQAAAAAAAAABAAAAEA==",
        "AAAAAAAAAAAAAAAGZmF1Y2V0AAAAAAABAAAAAAAAAAlyZWNpcGllbnQAAAAAAAATAAAAAA==",
        "AAAAAAAAAAAAAAAGc3ltYm9sAAAAAAAAAAAAAQAAABA=",
        "AAAAAAAAAAAAAAAHYXBwcm92ZQAAAAAEAAAAAAAAAARmcm9tAAAAEwAAAAAAAAAHc3BlbmRlcgAAAAATAAAAAAAAAAZhbW91bnQAAAAAAAsAAAAAAAAAEWV4cGlyYXRpb25fbGVkZ2VyAAAAAAAABAAAAAA=",
        "AAAAAAAAAAAAAAAHYmFsYW5jZQAAAAABAAAAAAAAAAJpZAAAAAAAEwAAAAEAAAAL",
        "AAAAAAAAAAAAAAAIZGVjaW1hbHMAAAAAAAAAAQAAAAQ=",
        "AAAAAAAAAAAAAAAIdHJhbnNmZXIAAAADAAAAAAAAAARmcm9tAAAAEwAAAAAAAAACdG8AAAAAABMAAAAAAAAABmFtb3VudAAAAAAACwAAAAA=",
        "AAAAAAAAAAAAAAAJYWxsb3dhbmNlAAAAAAAAAgAAAAAAAAAEZnJvbQAAABMAAAAAAAAAB3NwZW5kZXIAAAAAEwAAAAEAAAAL",
        "AAAAAAAAAAAAAAAJYnVybl9mcm9tAAAAAAAAAwAAAAAAAAAHc3BlbmRlcgAAAAATAAAAAAAAAARmcm9tAAAAEwAAAAAAAAAGYW1vdW50AAAAAAALAAAAAA==",
        "AAAAAAAAAAAAAAAKYXV0aG9yaXplZAAAAAAAAQAAAAAAAAACaWQAAAAAABMAAAABAAAAAQ==",
        "AAAAAAAAAAAAAAAKaW5pdGlhbGl6ZQAAAAAAAgAAAAAAAAAFYWRtaW4AAAAAAAATAAAAAAAAAAx0ZXN0bmV0X21vZGUAAAABAAAAAA==",
        "AAAAAAAAAAAAAAANdHJhbnNmZXJfZnJvbQAAAAAAAAQAAAAAAAAAB3NwZW5kZXIAAAAAEwAAAAAAAAAEZnJvbQAAABMAAAAAAAAAAnRvAAAAAAATAAAAAAAAAAZhbW91bnQAAAAAAAsAAAAA",
        "AAAAAAAAAAAAAAAOc2V0X2F1dGhvcml6ZWQAAAAAAAIAAAAAAAAAAmlkAAAAAAATAAAAAAAAAAlhdXRob3JpemUAAAAAAAABAAAAAA==",
        "AAAAAAAAAAAAAAARc3BlbmRhYmxlX2JhbGFuY2UAAAAAAAABAAAAAAAAAAJpZAAAAAAAEwAAAAEAAAAL",
      ]),
      options,
    );
  }

  public readonly fromJSON = {
    burn: this.txFromJSON<null>,
    mint: this.txFromJSON<null>,
    name: this.txFromJSON<string>,
    faucet: this.txFromJSON<null>,
    symbol: this.txFromJSON<string>,
    approve: this.txFromJSON<null>,
    balance: this.txFromJSON<i128>,
    decimals: this.txFromJSON<u32>,
    transfer: this.txFromJSON<null>,
    allowance: this.txFromJSON<i128>,
    burn_from: this.txFromJSON<null>,
    authorized: this.txFromJSON<boolean>,
    initialize: this.txFromJSON<null>,
    transfer_from: this.txFromJSON<null>,
    set_authorized: this.txFromJSON<null>,
    spendable_balance: this.txFromJSON<i128>,
  };
}
