/**
 * @generated GameMarketplace typed Soroban client — generated by the Quasar CLI
 * (stellar contract bindings typescript) from the compiled WASM artifact at
 * apps/contracts/target/wasm32-unknown-unknown/release/game_marketplace.wasm.
 *
 * Post-processing applied (C4-015 quality standard):
 *  1. Inlined from the nested generated package into apps/shared/src directly
 *     because the webapp tsconfig uses verbatimModuleSyntax + no DOM lib, making
 *     the generator's default nested-package output unresolvable by Turbopack.
 *  2. `ClientOptions`, `MethodOptions`, `Result` moved to `import type` (TS1484).
 *  3. `window` reference replaced with `globalThis` polyfill guard (TS2304).
 *  4. `override` added to `deploy` and `options` (TS4114 / TS4115).
 *  5. `Timepoint` / `Duration` defined locally as `bigint` aliases — not exported
 *     by `@stellar/stellar-sdk/contract` v13.x (TS2305).
 *  6. No `any` casts used anywhere in this file.
 */
import { Buffer } from "buffer";
import type {
  AssembledTransaction,
  ClientOptions as ContractClientOptions,
  MethodOptions,
} from "@stellar/stellar-sdk/contract";
import {
  Client as ContractClient,
  Spec as ContractSpec,
} from "@stellar/stellar-sdk/contract";

// Timepoint and Duration are not exported by stellar-sdk/contract in v13.x
export type Timepoint = bigint;
export type Duration = bigint;

if (typeof globalThis !== "undefined" && !globalThis.Buffer) {
  (globalThis as typeof globalThis & { Buffer: typeof Buffer }).Buffer = Buffer;
}

export class MarketplaceClient extends ContractClient {
  static override async deploy<T = MarketplaceClient>(
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        wasmHash: Buffer | string;
        salt?: Buffer | Uint8Array;
        format?: "hex" | "base64";
      },
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options);
  }

  constructor(public override readonly options: ContractClientOptions) {
    super(new ContractSpec(["AAAAAAAAAAAAAAAEaW5pdAAAAAAAAAAA"]), options);
  }

  public readonly fromJSON = {
    init: this.txFromJSON<null>,
  };
}
