name: Next.js Frontend CI

on:
  push:
    branches: ['main']
    paths:
      - 'packages/nextjs/**'
  pull_request:
    branches: ['main']
    paths:
      - 'packages/nextjs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('packages/nextjs/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install
        working-directory: packages/nextjs

      - name: Lint code
        run: bun run lint
        working-directory: packages/nextjs

      - name: Build application
        run: bun run build
        working-directory: packages/nextjs
